title: SuperH0ng
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://long-haul.netlify.app
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: SuperH0ng
  instagram : SuperH0ng_
  email: ghdtmdgus100@gmail.com

google_analytics: "UA-215199109-1"
comment :
  provider : "disqus"
  disqus :
    shortname : "SuperH0ng"

disqus:
    shortname: brianmaierjr
